# ======================== Elasticsearch Configuration =========================
#
# NOTE: Elasticsearch comes with reasonable defaults for most settings.
#       Before you set out to tweak and tune the configuration, make sure you
#       understand what are you trying to accomplish and the consequences.
#
# The primary way of configuring a node is via this file. This template lists
# the most important settings you may want to configure for a production cluster.
#
# Please see the documentation for further information on configuration options:
# <http://www.elastic.co/guide/en/elasticsearch/reference/current/setup-configuration.html>
#
# ---------------------------------- Cluster -----------------------------------
#
# Use a descriptive name for your cluster:
#
cluster.name: {{elasticsearch.cluster_name}}
# ------------------------------------ Index ------------------------------------
index.number_of_shards: {{elasticsearch.index_number_of_shards}}
index.number_of_replicas: {{elasticsearch.index_number_of_replicas}}
#indices.fielddata.cache.size: 40%
action.auto_create_index: {{elasticsearch.action_auto_create_index}}
# ------------------------------------ ThreadPool ------------------------------
threadpool.bulk.type: fixed
threadpool.bulk.size: 30

threadpool.search.type: fixed
threadpool.search.size: 30

# ------------------------------------ Node ------------------------------------
#
# Use a descriptive name for the node:
#
node.name: {{ ansible_nodename }}
#
# Add custom attributes to the node:
#
# node.rack: r1
node.master: {{hostvars[ansible_nodename].node_master}}
node.data: {{hostvars[ansible_nodename].node_data|default(True)}}
# ----------------------------------- Paths ------------------------------------
#
# Path to directory where to store the data (separate multiple locations by comma):
#
path.data: {{elasticsearch.path_data}}
#
# Path to log files:
path.logs: {{elasticsearch.path_logs}}
#
# ----------------------------------- Memory -----------------------------------
#
# Lock the memory on startup:
#
bootstrap.mlockall: {{elasticsearch.bootstrap_mlockall}}
#
# Make sure that the `ES_HEAP_SIZE` environment variable is set to about half the memory
# available on the system and that the owner of the process is allowed to use this limit.
#
# Elasticsearch performs poorly when the system is swapping the memory.
#
# ---------------------------------- Network -----------------------------------
#
# Set the bind address to a specific IP (IPv4 or IPv6):
#
network.host: 0.0.0.0
#
# Set a custom port for HTTP:
#
http.port: 9200
transport.tcp.port: 9300
transport.tcp.compress: true
http.max_content_length: 100mb
#
# For more information, see the documentation at:
# <http://www.elastic.co/guide/en/elasticsearch/reference/current/modules-network.html>
#
# --------------------------------- Discovery ----------------------------------
#
# Pass an initial list of hosts to perform discovery when new node is started:
# The default list of hosts is ["127.0.0.1", "[::1]"]
discovery.zen.ping.multicast.enabled: false
#

discovery.zen.ping.unicast.hosts: [{% for host in groups['elasticsearchs'] %}"{{ host }}"{% if not loop.last %},{% endif %}{% endfor %}]
#
# Prevent the "split brain" by configuring the majority of nodes (total number of nodes / 2 + 1):
{% for host in groups['elasticsearchs'] %}
{% if loop.first %}
{% set master=0 %}
{% set min_master=0 %}
{% endif %}
{% if hostvars[host].node_master==True %}{% set master=master+1 %}{% endif %}
{% if loop.last %}
{% set min_master=master//2+1 %}
discovery.zen.minimum_master_nodes: {{min_master}}
{% endif %}
{% endfor %}
# For more information, see the documentation at:
# <http://www.elastic.co/guide/en/elasticsearch/reference/current/modules-discovery.html>
#
# ---------------------------------- Gateway -----------------------------------
#
# Block initial recovery after a full cluster restart until N nodes are started:
#
gateway.recover_after_nodes: {% for host in groups['elasticsearchs'] %}{% if loop.last %}{{ loop.index-1 }}{% endif %}{% endfor %} 
gateway.recover_after_time: 1m
gateway.expected_nodes: {% for host in groups['elasticsearchs'] %}{% if loop.last %}{{ loop.index }}{% endif %}{% endfor %}

# For more information, see the documentation at:
# <http://www.elastic.co/guide/en/elasticsearch/reference/current/modules-gateway.html>
#
# ---------------------------------- Various -----------------------------------
#
# Disable starting multiple nodes on a single system:
#
# node.max_local_storage_nodes: 1
#
# Require explicit names when deleting indices:
#
# action.destructive_requires_name: true
#
# ---------------------------------- Analyzer -----------------------------------
